rendering.draw_animation { animation = "animation-laurel",
                           target = game. player.character,
                           target_offset = { 0, -5 },
                           surface = game.player.surface,
                           x_scale = 0.2,
                           y_scale = 0.2,
                           time_to_live = 144,
                           animation_speed = 1,
                           animation_offset = 0, }
