---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/12/28 22:23
---

local itemStack = 1000

--需要改大堆叠的物品名称
local items = {
    "mining-drone",
    "mining-depot",
    --运输车
    "supply-depot",
    "request-depot",
    "fuel-depot",
    "fuel-depots",
    "fluid-depot",
    "buffer-depot",
    "road",
    "fast-road",
    "transport-drone",
--    base
    "iron-plate",
    "stone",
    "landfill",
    "speed-module",
    "transport-belt",
    "underground-belt",
    "splitter",
    "inserter",
    "inserters",
    "long-handed-inserters",
    "fast-inserter",
    "fast-splitter",
    "fast-transport-belt",
    "fast-underground-belt",
    "filter-inserter",
    "stack-inserter",
    "pipe",
    "pipe-to-ground",
}

for i, itemName in pairs(items) do

    local dataItem = data.raw["item"][itemName]

    if dataItem then
        dataItem.stack_size = itemStack
    end

end



